### ISSUE TITLE
Odd button post-hover color

### ISSUE THREAD

**Issue by acoolstraw** [acoolstraw/earl-grey#1]
If you click on a button, hold, move your cursor away from the button and let go, a weird green will display that conflicts with the general blue color of the theme.
![image](https://user-images.githubusercontent.com/45886986/128327787-60616b3a-c956-418d-9b75-ad0c9fe41e01.png)
I have tried searching for the color inside of the theme, but no dice.

**Comment by Freeplayg** [comment]
That's the :focus state of the button. (Atleast in FireFox) you can check different states for the button and what it applies
![2021-08-10_07-42](https://user-images.githubusercontent.com/40742947/128861157-01bffee0-c77e-4252-b1c0-4b15479fa12a.png)

**Comment by Freeplayg** [comment]
Btw! Unrelated to this issue but the awesome-gitea repo is asking you to submit a pull request instead of an issue.

**Comment by acoolstraw** [comment]
Whoops, thanks for the heads up

**Comment by acoolstraw** [comment]
So about the :focus, changing anything with :focus does nothing, not sure what to change in order to see what causes it

**Comment by acoolstraw** [comment]
![image](https://user-images.githubusercontent.com/45886986/129266041-49c2bee0-dbbb-40a6-8697-5309f4fe0762.png)
ah

**Comment by acoolstraw** [comment]
should be fixed, but there could be more of those
