### ISSUE TITLE
This seems to be broken under the current frontend configuration.

### ISSUE THREAD

**Issue by nativeit** [acoolstraw/earl-grey#4]
I'm not sure if there's something specific to my instance, or if this is just the result of some of the recent refactoring efforts by Gitea devs, but after implementing everything just as described, my UI lacked almost all of the custom elements in your theme. The most glaring problem being the background, which for some reason has been overridden with the Fomantic CSS framework's default:

```
body {
  margin: 0;
  padding: 0;
  overflow-x: hidden;
  min-width: 320px;
  background: #FFFFFF;
  font-family: 'Roboto', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 14px;
  line-height: 1.4285em;
  color: rgba(0, 0, 0, 0.87);
}
```

This same problem crops up all over, none of the custom CSS rules make it through the framework's. If there's something right offhand you think I may be missing, let me know. Either way, if the refactoring has broken the ability for this kind of theme (and it seems like a lovely, welcome addition to the stock themes) then perhaps someone working on Gitea's frontend should find a way to keep Fomantic from stepping on the stylesheets in the custom dir?

**Comment by acoolstraw** [comment]
What version of Gitea are you running? Did you follow the installation instructions and is it now available as an option in the theme selector?

**Comment by nativeit** [comment]
My apologies. I deployed my instance from Proxmox using a Turnkey image, which was woefully outdated. I manually updated to `1.16.7` and this took care of it. 

It looks great, thanks very much for your work on this!

**Comment by acoolstraw** [comment]
Thank you for the kind words, glad it worked!
