### ISSUE TITLE
Support for gitea 1.18.0-rc0

### ISSUE THREAD

**Issue by flipkickmedia** [acoolstraw/earl-grey#5]
Some changes that need to be made to support gitea 1.18.0-rc0

I can see these additional icons in the profile area.

![image](https://user-images.githubusercontent.com/15732784/201217538-f205bf12-e415-449c-b0f7-3590fa394a6f.png)

**Comment by acoolstraw** [comment]
Huh, that's weird. I'll look into it

**Comment by acoolstraw** [comment]
It doesn't happen on my end. Was there anything you clicked to make the icons appear or are they there by default?

**Comment by flipkickmedia** [comment]
I made an image replacement in the head, and changed the landing page.  Let me narrow down which change is causing the problem.

**Comment by flipkickmedia** [comment]
Ok so I think I must have copied the templates from gitea master, and applied my changes.  Ive redone my changes using the correct gitea repo tag and the artifacts have gone.  False alert. Sorry for the noise.
